USE PROJECT_DB;

CREATE TABLE USERS ( USERNAME VARCHAR(20),
                    USERID INT IDENTITY(1,1) PRIMARY KEY,
					FIRSTNAME VARCHAR(30),
					LASTNAME VARCHAR(30));


CREATE TABLE COURSES (COURSEID INT PRIMARY KEY  IDENTITY(1000,1),
                       COURSECODE INT,
                       COURSENAME VARCHAR(100),
					   DESCRIPTION VARCHAR(500),
					   FEES DECIMAL(10,2),
					   DURATION INT,
					   QUALIFICATIONS VARCHAR(50),
					   MODULES VARCHAR(50));

CREATE TABLE ENQUIRER (ENQUIRYCODE INT IDENTITY(1,1),
                       ENQUIRERPROFILEID INT  ,
                       NAME VARCHAR(30),DOB DATE,
					   EMAIL VARCHAR(50),
					   NUMBER INT,ADDRESS VARCHAR(200),
					   HIGHEST_QUALIFICATION VARCHAR(40),
					   MARKS DECIMAL(10,1),
					   PASSOUTRYEAR INT,
					   RESOURCENAME VARCHAR(40),
					   ENQUIREDCOURSE VARCHAR(100),
					   ENQUIRYDATE DATE,
					   ENQUIRYSTATUS VARCHAR(50), 
					   PRIMARY KEY(ENQUIRERPROFILEID,ENQUIRYCODE));

CREATE TABLE ENQUIRY_MANAGEMENT(ENQUIRYCODE INT PRIMARY KEY,
                                 ENQUIRYPROFILEID INT FOREIGN KEY REFERENCES ENQUIRER(ENQUIRERPROFILEID) );


CREATE TABLE QUALIFICATION (QUALIFICATIONID INT PRIMARY KEY,
                            QUALIFICATIONNAME VARCHAR(30),
							COURSEID INT FOREIGN KEY REFERENCES COURSES(COURSEID));

CREATE TABLE MODULES(MOUDULEID INT PRIMARY KEY,
                     MODULENAME VARCHAR(20),
					 COURSEID INT FOREIGN KEY REFERENCES COURSES(COURSEID));


CREATE TABLE RESOURSE(RESOURSEID INT PRIMARY KEY,
                RESOURSENAME VARCHAR(20));